language: php
php:
- 5.6
- 5.5
- 5.4
before_script:
- composer install --dev
script:
- make lint
- make test
after_success:
- make coveralls
- '[[ -n "${TRAVIS_TAG}" ]] && make gh-pages'
env:
  global:
    secure: PLLi+L7TaO+woxBSyvduOgRVcqmWJHnEn9KdgCHJOh0ZC5Gsg7xe8KZIo6apO1q3x8+TBDJeWVqk/u2pJDLVLYiEWnQtJRPtGhyR2td7mL6i+Mi+EtKfN/QYtyJXC9Ti/1NUWmPvbtBRdp3SXFJJPGX+3yB/WQb1xG0T/O5ZvSE=
